import type { Metadata } from "next";
import Link from "next/link";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import NewsletterSignup from "@/components/NewsletterSignup";
import SupportCTA from "@/components/SupportCTA";
import { AI_TOOL_SLUGS, DEFAULT_FREE_DAILY_LIMIT } from "@/utils/aiConfig";
import { tools } from "@/data/tools";
import { absoluteUrl } from "@/data/site";

export const metadata: Metadata = {
  title: "Free AI Creator Tools",
  description:
    "Free Gemini-powered AI creator tools for hooks, captions, hashtags, titles, posts, emails, summaries and product copy. Five free generations per day.",
  alternates: { canonical: absoluteUrl("/ai-tools") },
  openGraph: {
    title: "Free AI Creator Tools | A2ZConvertor",
    description:
      "Use free Gemini-powered creator and writing tools with no account required.",
    url: absoluteUrl("/ai-tools"),
  },
};

const aiTools = AI_TOOL_SLUGS.map((slug) => tools.find((tool) => tool.slug === slug)).filter((tool): tool is (typeof tools)[number] => Boolean(tool));

const faqs = [
  ["Are these AI creator tools free?", `Yes. A2ZConvertor currently provides ${DEFAULT_FREE_DAILY_LIMIT} owner-funded Gemini generations per day at no charge.`],
  ["Do these tools guarantee growth?", "No. They create editable ideas and drafts, but they cannot guarantee followers, reach, engagement, rankings or sales."],
  ["Do I need to create an account or add an API key?", "No. The public tools work through A2ZConvertor's configured Gemini connection."],
  ["What happens when I reach the daily limit?", "Try again the next day, or support A2ZConvertor to help fund higher free limits."],
  ["Should I publish generated content without editing?", "No. Review facts, tone and brand fit before publishing anything generated by AI."],
];

const resourceLinks = [
  ["AI hook ideas", "/resources/ai-hook-ideas"],
  ["Carousel post ideas", "/resources/carousel-post-ideas"],
  ["LinkedIn post ideas", "/resources/linkedin-post-ideas"],
  ["Short video script ideas", "/resources/short-video-script-ideas"],
];

export default function AIToolsPage() {
  return <main className="min-h-screen bg-slate-950 text-white">
    <Navbar />
    <section className="px-6 pb-14 pt-20">
      <div className="mx-auto max-w-6xl">
        <span className="rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-sm font-bold text-emerald-300">Free AI {"\u00b7"} {DEFAULT_FREE_DAILY_LIMIT}/day</span>
        <h1 className="mt-5 text-5xl font-black md:text-6xl">Free AI Creator Tools</h1>
        <p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Create hooks, captions, hashtags, titles, emails, summaries, bios, product copy and content ideas with Gemini. You receive {DEFAULT_FREE_DAILY_LIMIT} free generations per day, with no account or API key required.</p>
        <div className="mt-8 flex flex-wrap gap-3">
          <Link href="#tools" className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white hover:bg-blue-500">Browse AI tools</Link>
          <Link href="/support" className="rounded-xl border border-white/10 px-5 py-3 font-semibold text-slate-200 hover:border-blue-500/60">Support free AI</Link>
        </div>
      </div>
    </section>

    <section id="tools" className="px-6 pb-20">
      <div className="mx-auto grid max-w-6xl gap-5 sm:grid-cols-2 lg:grid-cols-3">
        {aiTools.map((tool) => <Link key={tool.slug} href={`/convert/${tool.slug}`} className="flex min-h-56 flex-col rounded-2xl border border-white/10 bg-slate-900/70 p-6 hover:border-blue-500/60">
          <p className="text-xs font-bold uppercase text-blue-300">{tool.category}</p>
          <h2 className="mt-3 text-xl font-bold">{tool.name}</h2>
          <p className="mt-3 text-slate-400">{tool.description}</p>
          <span className="mt-auto pt-5 font-semibold text-blue-300">Try free AI tool</span>
        </Link>)}
      </div>
    </section>

    <section className="border-y border-white/10 bg-slate-900/40 px-6 py-16">
      <div className="mx-auto grid max-w-6xl gap-6 md:grid-cols-3">
        <div className="md:col-span-1">
          <h2 className="text-3xl font-black">Create faster, edit smarter</h2>
          <p className="mt-4 leading-7 text-slate-400">These tools are built for fast first drafts. Use them for angles, outlines and copy options, then add your real facts, examples and judgement.</p>
        </div>
        <div className="grid gap-4 md:col-span-2 sm:grid-cols-2">
          {resourceLinks.map(([label, href]) => <Link key={href} href={href} className="rounded-2xl border border-white/10 bg-slate-950/60 p-5 font-semibold text-slate-200 hover:border-blue-500/60">{label}</Link>)}
          <Link href="/social-media-tools" className="rounded-2xl border border-white/10 bg-slate-950/60 p-5 font-semibold text-slate-200 hover:border-blue-500/60">Social Media Tools</Link>
          <Link href="/text-tools" className="rounded-2xl border border-white/10 bg-slate-950/60 p-5 font-semibold text-slate-200 hover:border-blue-500/60">Text Tools</Link>
        </div>
      </div>
    </section>

    <section className="px-6 py-20">
      <div className="mx-auto max-w-4xl">
        <h2 className="text-3xl font-black">Frequently asked questions</h2>
        <div className="mt-7 space-y-4">{faqs.map(([question, answer]) => <div key={question} className="rounded-2xl border border-white/10 bg-slate-900/70 p-6"><h3 className="font-bold">{question}</h3><p className="mt-2 text-slate-400">{answer}</p></div>)}</div>
      </div>
    </section>

    <NewsletterSignup />
    <SupportCTA />
    <Footer />
  </main>;
}
