import type { Metadata } from "next";
import Link from "next/link";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import { BUY_ME_A_COFFEE_URL } from "@/components/SupportCTA";
import { absoluteUrl } from "@/data/site";

export const metadata: Metadata = { title: "Support A2ZConvertor", description: "Help keep A2ZConvertor free and support hosting, AI generations and new tool development.", alternates: { canonical: absoluteUrl("/support") }, openGraph: { title: "Support A2ZConvertor", description: "Help keep free browser tools and limited AI generation available.", url: absoluteUrl("/support") } };
export default function SupportPage() { return <main className="min-h-screen bg-slate-950 text-white"><Navbar/><section className="px-6 py-20"><div className="mx-auto max-w-4xl"><p className="text-sm font-bold uppercase text-amber-200">Support the project</p><h1 className="mt-3 text-5xl font-black">Help keep A2ZConvertor free</h1><p className="mt-6 text-lg leading-8 text-slate-300">A2ZConvertor is free to use and requires no account. Hosting, AI generations, development and testing still have real costs. Voluntary support helps us maintain existing tools, improve free limits and build requested features responsibly.</p><a href={BUY_ME_A_COFFEE_URL} target="_blank" rel="noreferrer" className="mt-8 inline-flex rounded-xl bg-amber-300 px-6 py-3 font-bold text-slate-950 hover:bg-amber-200">Buy Me a Coffee</a><div className="mt-14 grid gap-5 md:grid-cols-3">{[["Request a Tool","/request-tool","Suggest the workflow that would save you time."],["Explore AI Tools","/ai-tools","Use the free Gemini-powered writing and creator tools."],["Advertise or Partner","/advertise","Discuss relevant sponsorship and partnership opportunities."]].map(([title,href,body])=><Link key={href} href={href} className="rounded-2xl border border-white/10 bg-slate-900/70 p-6 hover:border-amber-300/40"><h2 className="text-xl font-bold">{title}</h2><p className="mt-3 text-slate-400">{body}</p></Link>)}</div></div></section><Footer/></main>; }
